/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - ssotme odxml42/odxml-to-csharp-pocos
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace plantumldotnetparser.Lib.DataClasses
{                   
    
    public partial class Keyword 
    {
        public Keyword()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("Keyword: {0}", this.Name);
        }
                            
    }
}