/*************************************************
Initially Generated by SSoT.me - 2022
    EJ Alexandra - ssotme odxml42/odxml-to-csharp-pocos
    This be overwritten
*************************************************/
using System;
using System.ComponentModel;
                        
namespace plantumldotnetparser.Lib.DataClasses
{                   
    
    public partial class Keyword 
    {
    
        private static Keyword _title = new Keyword() {
            Name = "title",
            KeywordText = "title"
        };
        public static Keyword @title { get { return _title; } }
        private static Keyword _stop = new Keyword() {
            Name = "stop",
            KeywordText = "stop"
        };
        public static Keyword @stop { get { return _stop; } }
        private static Keyword _start = new Keyword() {
            Name = "start",
            KeywordText = "start"
        };
        public static Keyword @start { get { return _start; } }
        private static Keyword _enduml = new Keyword() {
            Name = "enduml",
            KeywordText = "@enduml"
        };
        public static Keyword @enduml { get { return _enduml; } }
        private static Keyword _as = new Keyword() {
            Name = "as",
            KeywordText = "as"
        };
        public static Keyword @as { get { return _as; } }
        private static Keyword _startuml = new Keyword() {
            Name = "startuml",
            KeywordText = "@startuml"
        };
        public static Keyword @startuml { get { return _startuml; } }
    }
}